# Tomcat
#server:
#  port: 9203

#spring
spring:
  datasource:
    url: jdbc:mysql://192.168.8.62:3306/yuanqu?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: remote
    password: remote
    driverClassName: com.mysql.cj.jdbc.Driver
#  application:
#    # 应用名称
#    name: co-system
#    profiles:
#      # 环境配置
#      active: public
#    cloud:
#      nacos:
#        discovery:
#          # 服务注册地址
#          server-addr: 192.168.8.98:8848
#          namespace: ${spring.profiles.active}
#        config:
#          # 配置中心地址
#          server-addr: 192.168.8.98:8848
#          # 配置文件格式
#          file-extension: yml
#          # 共享配置
#          shared-configs:
#            - application.${spring.cloud.nacos.config.file-extension}
#          namespace: ${spring.profiles.active}

# mybatis配置
mybatis:
  # 驼峰命名
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 搜索指定包别名
  type-aliases-package: com.alphaess.system
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath:mapper/**/*.xml

# swagger配置
swagger:
  title: 系统模块接口文档
