# Tomcat
#server:
#  port: 9203

#spring
spring:
  datasource:
    url: jdbc:mysql://192.168.8.62:3306/yuanqu?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: remote
    password: remote
    driverClassName: com.mysql.cj.jdbc.Driver
#  application:
#    # 应用名称
#    name: co-system
#    profiles:
#      # 环境配置
#      active: public
#    cloud:
#      nacos:
#        discovery:
#          # 服务注册地址
#          server-addr: 192.168.8.98:8848
#          namespace: ${spring.profiles.active}
#        config:
#          # 配置中心地址
#          server-addr: 192.168.8.98:8848
#          # 配置文件格式
#          file-extension: yml
#          # 共享配置
#          shared-configs:
#            - application.${spring.cloud.nacos.config.file-extension}
#          namespace: ${spring.profiles.active}
  redis:
    #redis数据库索引（默认为0）
    database: 10
    #Redis服务器地址
    host: 127.0.0.1
    #    #Redis服务器连接端口
    port: 6379
    #redis服务器连接密码（默认为空）
#    password: AlphaESS1234
    # 连接超时时间（毫秒）
    timeout: 10000
      # cluster:
      # nodes:
      # - 192.168.8.62:6379
    # - 192.168.8.77:7000
    # - 192.168.8.78:7000
    # - 192.168.8.79:7000
    # max-redirects: 3 #获取失败 最大重定向次数
    #lettuce
    lettuce:
      pool:
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
      # 关闭超时时间
      shutdown-timeout: 100

# mybatis配置
mybatis:
  # 驼峰命名
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 搜索指定包别名
  type-aliases-package: com.alphaess.system
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath:mapper/**/*.xml

# swagger配置
swagger:
  title: 系统模块接口文档
